###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "2Cool Blog",
  "author": "Diego Castillo",
  "url": "http://bogus.xyz",
  "likes": 42
}

###
GET http://localhost:3003/api/users
Content-Type: application/json

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "ashketchum",
  "password": "itsyouandme",
  "name": "Ash Ketchum"

}